name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: '${{ secrets.GCP_PROJECT_ID }}'

      - name: Build Docker image
        run: |
          docker pull ac7x/next-line-liff-template:latest || true
          docker build \
            --cache-from=ac7x/next-line-liff-template:latest \
            --build-arg NEXT_PUBLIC_LIFF_ID=${{ secrets.NEXT_PUBLIC_LIFF_ID }} \
            -t ac7x/next-line-liff-template:latest .
          echo "Docker image built successfully."

      - name: Push Docker image to Docker Hub
        run: |
          docker push ac7x/next-line-liff-template:latest
          echo "Docker image pushed successfully."

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: next-line-liff-template
          image: ac7x/next-line-liff-template:latest
          region: asia-east1
          project_id: ${{ secrets.GCP_PROJECT_ID }}
