name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: '${{ secrets.GCP_PROJECT_ID }}'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker buildx build \
            --cache-from=type=registry,ref=ac7x/next-line-liff-template:latest \
            --build-arg NEXT_PUBLIC_LIFF_ID=${{ secrets.NEXT_PUBLIC_LIFF_ID }} \
            --tag ac7x/next-line-liff-template:latest \
            --output type=docker .
          echo "Docker image built successfully."

      - name: Push Docker image to Docker Hub
        run: |
          docker push ac7x/next-line-liff-template:latest
          echo "Docker image pushed successfully."

      - uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: next-line-liff-template
          image: ac7x/next-line-liff-template:latest
          region: asia-east1
          project_id: ${{ secrets.GCP_PROJECT_ID }}
